### PR TITLE
Introducing google-cloud-bigtable-emulator

### LINKED ISSUE #1957: no way to programatically set credentials when using cbt emulator
Using BIGTABLE_EMULATOR_HOST is a reasonable solution for trying things out, but when using something like testcontainers to unit test with cbt emulator in a container with an unpredictable port it's not possible to set environment variables.

It would be very helpful if there was a way to set credentials programatically as can be done with BigtableOptions in the normal client, or GoogleCredentials and similar with storage and other products.

### PR DESCRIPTION
**Pull request by rahulKQL**
Fixes #1957 

## What this PR contains:
- Added instruction to programmatically set host & port in case of running this client in containers.
- Introduced new Google-cloud-emulator (inspired by [this](https://github.com/googleapis/cloud-bigtable-client/pull/2157#issuecomment-491359555) comment).

### CODE REVIEW

**Comment by rahulKQL** [comment]
@igorbernstein2 Whenever get a chance, Please have a look.

**Comment by igorbernstein2** [comment]
I think we should start directing users to https://github.com/googleapis/google-cloud-java/tree/master/google-cloud-testing/google-cloud-bigtable-emulator.

Docker adds too much complexity

**Comment by rahulKQL** [comment]
@igorbernstein2 I have removed the docker related instruction from this PR. Please have a fresh look.

**Comment by igorbernstein2** [comment]
I think we should move the docs for connecting to the emulator to the main readme. And change the docs in the maven plugin to direct people to use the gcj emulator

**Pull request merged**
