### PR TITLE
[WIP] Adding integration test for BigtableIO to read from bigtable

### PR DESCRIPTION
**Pull request by rahulKQL**
- Added `CloudBigtableBeamITTest#testReadFromBigtableIO`.
- Bumped up the row count to **100_000**, To standardize with other dataflow jobs.

**NOTE:** Currently facing issue related to shaded netty jar summarized [here](https://gist.github.com/rahulKQL/c38594a2cbd08f1dc149b3559249050d#dependencies).

### CODE REVIEW

**Comment by sduskis** [comment]
@rahulKQL, is this a work in progress PR, or is it ready for review?  If it's ready, please remove "WIP: " from the titlel

**Comment by rahulKQL** [comment]
@sduskis, Sorry for the stale PR. I think I am currently out of ideas on how to get it to work. I am facing conflicts on `NativeLibraryUtil` dues to shaded bigtable-hbase dependencies.

For now, I have shifted my focus on other tasks. I am closing this PR now and would probably create a new PR after finishing this work.

**Comment by sduskis** [comment]
Basically, you need to use the shaded version of the Cloud Bigtable IO client.  You can definitely do that in a new maven project.  @igorbernstein2 might have some other ideas.

**Comment by rahulKQL** [comment]
@sduskis Thanks for the suggestion!!. Would discuss this with @igorbernstein2 probably on next meetup and finish this work.

**Pull request closed without merging**
